name: bootloader

on:
  push:
    paths:
      - 'bootloader/**'
      - '.github/workflows/bootloader.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bootloader
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rust-src
      - name: Run tests
        run: cargo test --verbose --target x86_64-unknown-linux-gnu -Z build-std=core,alloc,test,panic_unwind
