name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          args: --no-default-features
          override: true
      - name: Test
        run: |
          cargo test --verbose --target ${{ matrix.target }}-unknown-linux-gnu
      - name: Build
        run: |
          ARCH=${{ matrix.target }} PROFILE=release ./build.sh