name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup component add rust-src

      - name: install Qemu if necessary
        if: ${{ matrix.arch }} != x86_64
        run: sudo apt-get install -y qemu-user

      - name: Test
        run: |
          cargo test --verbose --target ${{ matrix.arch }}-unknown-linux-gnu -Zbuild-std=core,alloc

      - run: sudo apt-get install -y llvm # For the tools (llvm-strip etc.)

      - name: Build
        run: |
          ARCH=${{ matrix.arch }} PROFILE=release PROFILE_OPTION=--release ./build.sh