name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --verbose --target ${{ matrix.target }}
      - name: Build
        run: |
          ./build.sh