name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup show
          rustup toolchain install nightly
          rustup default nightly
          rustup target add ${{ matrix.target }}-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-${{ matrix.target }}-unknown-linux-gnu
      - name: Test
        run: |
          cargo test --verbose --target ${{ matrix.target }}-unknown-linux-gnu
      - name: Build
        run: |
          ARCH=${{ matrix.target }} PROFILE=release ./build.sh