name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup component add rust-src

      - name: install Qemu
        run: sudo apt-get install -y qemu-user

      - run: sudo apt-get install -y llvm lld # For the tools (llvm-strip etc.)

      - name: install aarch64 C library
        if: matrix.arch == 'aarch64'
        run: sudo apt-get install -y libc6-dev-arm64-cross libgcc-12-dev-arm64-cross

      - name: Get additional RUSTFLAGS for cross compilation
        if: matrix.arch == 'aarch64'
        run: echo "CROSS_COMPILE_RUSTFLAGS=-C link-arg=--sysroot=/usr/aarch64-linux-gnu -C link-arg=-Wl,--sysroot=/" >> $GITHUB_ENV

      - name: set up aarch64 dynamic linker
        if: matrix.arch == 'aarch64'
        run: |
          echo "#!/bin/sh" >> ld-aarch64.sh
          echo "# Fake ld-linux-aarch64.so.1 which passes some parameters to the real one under /usr/aarch64-linux-gnu" >> ld-aarch64.sh
          echo "/usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 --library-path /usr/aarch64-linux-gnu/lib $@" >> ld-aarch64.sh
          sudo cp ld-aarch64.sh /lib/ld-linux-aarch64.so.1

      - name: Test
        env:
          RUSTFLAGS: -C linker=clang -C linker-flavor=gcc -C link-arg=-fuse-ld=lld -C link-arg=--target=${{ matrix.arch }}-unknown-linux-gnu ${{ env.CROSS_COMPILE_RUSTFLAGS }}
        run: |
          cargo test --verbose --target ${{ matrix.arch }}-unknown-linux-gnu -Z build-std=core,alloc,test,panic_unwind

      - name: Build
        run: |
          ARCH=${{ matrix.arch }} PROFILE=release PROFILE_OPTION=--release SOURCED_CONFIG=y ./build.sh
