name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86_64", "aarch64"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          rustup target add ${{ matrix.arch }}-unknown-linux-gnu || true
          cargo test --verbose --target ${{ matrix.arch }}-unknown-linux-gnu
      - name: Build
        run: |
          rustup default nightly
          ARCH=${{ matrix.arch }} PROFILE=release ./build.sh

