name: kernel-build

on:
  push:
    paths:
      - 'kernel/**'
      - '.github/workflows/kernel.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./kernel
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup component add rust-src

      - name: install Qemu
        run: sudo apt-get install -y qemu-user

      - run: sudo apt-get install -y llvm lld # For the tools (llvm-strip etc.)

      - name: Test
        env:
          RUSTFLAGS: -C linker=clang -C linker-flavor=gcc -C linker-arg=-fuse-ld=lld
        run: |
          cargo test --verbose --target ${{ matrix.arch }}-unknown-linux-gnu -Z build-std=core,alloc,test,panic_unwind

      - name: Build
        run: |
          ARCH=${{ matrix.arch }} PROFILE=release PROFILE_OPTION=--release SOURCED_CONFIG=y ./build.sh
